"""add_all_models

Revision ID: 72c02b9d8f35
Revises: 7e2202dec93c
Create Date: 2025-11-04 06:25:10.652958+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '72c02b9d8f35'
down_revision: Union[str, None] = '7e2202dec93c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('easypost_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('street1', sa.String(length=200), nullable=False),
    sa.Column('street2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('verifications', sa.JSON(), nullable=True),
    sa.Column('is_residential', sa.Boolean(), nullable=True),
    sa.Column('carrier_facility', sa.String(length=50), nullable=True),
    sa.Column('federal_tax_id', sa.String(length=20), nullable=True),
    sa.Column('state_tax_id', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_easypost_id'), 'addresses', ['easypost_id'], unique=True)
    op.create_table('analytics_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('total_shipments', sa.Integer(), nullable=False),
    sa.Column('successful_shipments', sa.Integer(), nullable=False),
    sa.Column('failed_shipments', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('average_cost_per_shipment', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('average_delivery_days', sa.Float(), nullable=True),
    sa.Column('on_time_delivery_rate', sa.Float(), nullable=True),
    sa.Column('carrier_stats', sa.JSON(), nullable=True),
    sa.Column('top_destinations', sa.JSON(), nullable=True),
    sa.Column('domestic_vs_international', sa.JSON(), nullable=True),
    sa.Column('service_breakdown', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_summaries_date'), 'analytics_summaries', ['date'], unique=False)
    op.create_table('batch_operations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.String(length=50), nullable=False),
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('processed_items', sa.Integer(), nullable=False),
    sa.Column('successful_items', sa.Integer(), nullable=False),
    sa.Column('failed_items', sa.Integer(), nullable=False),
    sa.Column('total_processing_time', sa.Float(), nullable=True),
    sa.Column('avg_item_time', sa.Float(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_operations_batch_id'), 'batch_operations', ['batch_id'], unique=True)
    op.create_table('carrier_performance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('carrier', sa.String(length=50), nullable=False),
    sa.Column('service', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('total_shipments', sa.Integer(), nullable=False),
    sa.Column('on_time_deliveries', sa.Integer(), nullable=False),
    sa.Column('delayed_deliveries', sa.Integer(), nullable=False),
    sa.Column('failed_deliveries', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('average_cost', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('average_delivery_days', sa.Float(), nullable=True),
    sa.Column('min_delivery_days', sa.Integer(), nullable=True),
    sa.Column('max_delivery_days', sa.Integer(), nullable=True),
    sa.Column('on_time_rate', sa.Float(), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carrier_performance_carrier'), 'carrier_performance', ['carrier'], unique=False)
    op.create_index(op.f('ix_carrier_performance_date'), 'carrier_performance', ['date'], unique=False)
    op.create_index(op.f('ix_carrier_performance_service'), 'carrier_performance', ['service'], unique=False)
    op.create_table('customs_infos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('easypost_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('contents_type', sa.String(length=50), nullable=False),
    sa.Column('contents_explanation', sa.Text(), nullable=True),
    sa.Column('customs_certify', sa.Boolean(), nullable=False),
    sa.Column('customs_signer', sa.String(length=100), nullable=True),
    sa.Column('non_delivery_option', sa.String(length=20), nullable=False),
    sa.Column('restriction_type', sa.String(length=20), nullable=False),
    sa.Column('restriction_comments', sa.Text(), nullable=True),
    sa.Column('customs_items', sa.JSON(), nullable=True),
    sa.Column('eel_pfc', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customs_infos_easypost_id'), 'customs_infos', ['easypost_id'], unique=True)
    op.create_table('parcels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('easypost_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('predefined_package', sa.String(length=50), nullable=True),
    sa.Column('mass_unit', sa.String(length=10), nullable=False),
    sa.Column('distance_unit', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcels_easypost_id'), 'parcels', ['easypost_id'], unique=True)
    op.create_table('system_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('active_connections', sa.Integer(), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('error_rate', sa.Float(), nullable=True),
    sa.Column('avg_response_time_ms', sa.Float(), nullable=True),
    sa.Column('p95_response_time_ms', sa.Float(), nullable=True),
    sa.Column('p99_response_time_ms', sa.Float(), nullable=True),
    sa.Column('cpu_usage_percent', sa.Float(), nullable=True),
    sa.Column('memory_usage_mb', sa.Float(), nullable=True),
    sa.Column('disk_usage_percent', sa.Float(), nullable=True),
    sa.Column('db_connections_active', sa.Integer(), nullable=False),
    sa.Column('db_connections_idle', sa.Integer(), nullable=False),
    sa.Column('db_query_count', sa.Integer(), nullable=False),
    sa.Column('db_slow_queries', sa.Integer(), nullable=False),
    sa.Column('easypost_requests', sa.Integer(), nullable=False),
    sa.Column('easypost_errors', sa.Integer(), nullable=False),
    sa.Column('easypost_avg_response_time_ms', sa.Float(), nullable=True),
    sa.Column('cache_hit_rate', sa.Float(), nullable=True),
    sa.Column('cache_miss_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_metrics_timestamp'), 'system_metrics', ['timestamp'], unique=False)
    op.create_table('user_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('endpoint', sa.String(length=200), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_activities_session_id'), 'user_activities', ['session_id'], unique=False)
    op.create_index(op.f('ix_user_activities_timestamp'), 'user_activities', ['timestamp'], unique=False)
    op.create_index(op.f('ix_user_activities_user_id'), 'user_activities', ['user_id'], unique=False)
    op.create_table('shipments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('easypost_id', sa.String(length=50), nullable=False),
    sa.Column('tracking_code', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('from_address_id', sa.UUID(), nullable=False),
    sa.Column('to_address_id', sa.UUID(), nullable=False),
    sa.Column('return_address_id', sa.UUID(), nullable=True),
    sa.Column('buyer_address_id', sa.UUID(), nullable=True),
    sa.Column('parcel_id', sa.UUID(), nullable=False),
    sa.Column('customs_info_id', sa.UUID(), nullable=True),
    sa.Column('selected_rate_id', sa.String(length=50), nullable=True),
    sa.Column('rates_data', sa.JSON(), nullable=True),
    sa.Column('base_cost', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('carrier', sa.String(length=50), nullable=True),
    sa.Column('service', sa.String(length=50), nullable=True),
    sa.Column('delivery_days', sa.Integer(), nullable=True),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.Column('tracking_details', sa.JSON(), nullable=True),
    sa.Column('signed_by', sa.String(length=100), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('est_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('batch_id', sa.String(length=50), nullable=True),
    sa.Column('batch_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['buyer_address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['customs_info_id'], ['customs_infos.id'], ),
    sa.ForeignKeyConstraint(['from_address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ),
    sa.ForeignKeyConstraint(['return_address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['to_address_id'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_easypost_id'), 'shipments', ['easypost_id'], unique=True)
    op.create_index(op.f('ix_shipments_tracking_code'), 'shipments', ['tracking_code'], unique=False)
    op.create_table('shipment_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('carrier_status', sa.String(length=100), nullable=True),
    sa.Column('tracking_location', sa.JSON(), nullable=True),
    sa.Column('event_datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipment_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('creation_to_purchase_time', sa.Float(), nullable=True),
    sa.Column('purchase_to_label_time', sa.Float(), nullable=True),
    sa.Column('total_processing_time', sa.Float(), nullable=True),
    sa.Column('base_rate', sa.Float(), nullable=True),
    sa.Column('fuel_surcharge', sa.Float(), nullable=True),
    sa.Column('insurance_cost', sa.Float(), nullable=True),
    sa.Column('tracking_cost', sa.Float(), nullable=True),
    sa.Column('other_fees', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('estimated_delivery_days', sa.Integer(), nullable=True),
    sa.Column('actual_delivery_days', sa.Integer(), nullable=True),
    sa.Column('delivery_delay_days', sa.Integer(), nullable=True),
    sa.Column('was_on_time', sa.Boolean(), nullable=True),
    sa.Column('tracking_updates_count', sa.Integer(), nullable=False),
    sa.Column('exception_events_count', sa.Integer(), nullable=False),
    sa.Column('delivery_attempts', sa.Integer(), nullable=False),
    sa.Column('origin_country', sa.String(length=2), nullable=True),
    sa.Column('destination_country', sa.String(length=2), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('carrier', sa.String(length=50), nullable=True),
    sa.Column('service', sa.String(length=50), nullable=True),
    sa.Column('package_type', sa.String(length=50), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipment_metrics')
    op.drop_table('shipment_events')
    op.drop_index(op.f('ix_shipments_tracking_code'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_easypost_id'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_user_activities_user_id'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_timestamp'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_session_id'), table_name='user_activities')
    op.drop_table('user_activities')
    op.drop_index(op.f('ix_system_metrics_timestamp'), table_name='system_metrics')
    op.drop_table('system_metrics')
    op.drop_index(op.f('ix_parcels_easypost_id'), table_name='parcels')
    op.drop_table('parcels')
    op.drop_index(op.f('ix_customs_infos_easypost_id'), table_name='customs_infos')
    op.drop_table('customs_infos')
    op.drop_index(op.f('ix_carrier_performance_service'), table_name='carrier_performance')
    op.drop_index(op.f('ix_carrier_performance_date'), table_name='carrier_performance')
    op.drop_index(op.f('ix_carrier_performance_carrier'), table_name='carrier_performance')
    op.drop_table('carrier_performance')
    op.drop_index(op.f('ix_batch_operations_batch_id'), table_name='batch_operations')
    op.drop_table('batch_operations')
    op.drop_index(op.f('ix_analytics_summaries_date'), table_name='analytics_summaries')
    op.drop_table('analytics_summaries')
    op.drop_index(op.f('ix_addresses_easypost_id'), table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
