"""Product categorisation utilities."""

from __future__ import annotations

from typing import Dict, List

# Product category detection patterns (ORDER MATTERS - checked sequentially)
# More specific categories first to avoid false matches
PRODUCT_CATEGORIES: Dict[str, List[str]] = {
    "apparel": [
        "jeans",
        "shirt",
        "pants",
        "jacket",
        "dress",
        "skirt",
        "shorts",
        "sweater",
        "hoodie",
        "coat",
        "clothing",
        "apparel",
        "denim",
        "selvedge",
        "vintage",
        "t-shirt",
        "blouse",
        "polo",
        "cardigan",
        "vest",
        "suit",
        "blazer",
        "trousers",
        "leggings",
        "joggers",
        "sweatpants",
        "tank top",
        "crop top",
        "underwear",
        "socks",
        "mens",
        "womens",
        "unisex",
        "slim-fit",
        "straight-leg",
        "boot cut",
        "tapered",
    ],
    "footwear": [
        "shoes",
        "boots",
        "sneakers",
        "sandals",
        "slippers",
        "heels",
        "flats",
        "loafers",
        "oxfords",
        "athletic shoes",
        "running shoes",
        "basketball shoes",
        "cleats",
        "flip-flops",
    ],
    "sporting": [
        "fishing",
        "reel",
        "rod",
        "tackle",
        "outdoor",
        "camping",
        "hunting",
        "baseball",
        "glove",
        "bat",
        "sports",
        "athletic",
        "fitness",
        "golf",
        "tennis",
        "soccer",
        "basketball",
        "football",
        "hockey",
        "bike",
        "cycling",
        "yoga",
        "exercise",
        "hiking",
        "climbing",
        "skiing",
        "snowboard",
        "skateboard",
        "surfboard",
        "kayak",
        "gym",
        "workout",
        "training",
        "running",
        "swimming",
        "boxing",
        "martial arts",
    ],
    "electronics": [
        "phone",
        "computer",
        "tablet",
        "headphone",
        "speaker",
        "camera",
        "laptop",
        "monitor",
        "keyboard",
        "mouse",
        "gaming",
        "console",
        "smartwatch",
        "earbuds",
        "wireless",
        "bluetooth",
        "usb",
        "charger",
        "adapter",
        "electronics",
        "tech",
        "gadget",
        "device",
    ],
    "beauty": [
        "cosmetic",
        "skincare",
        "makeup",
        "foundation",
        "lipstick",
        "mascara",
        "eyeshadow",
        "cleanser",
        "moisturizer",
        "toner",
        "face mask",
        "beauty",
        "nail polish",
        "fragrance",
        "perfume",
        "cologne",
        "lotion",
        "cream",
        "serum",
    ],
    "bedding": [
        "pillow",
        "mattress",
        "sheet",
        "blanket",
        "comforter",
        "duvet",
        "bedding",
        "linen",
        "pillowcase",
        "fitted sheet",
        "flat sheet",
        "bed",
        "sleeping",
        "quilt",
        "coverlet",
    ],
    "art": [
        "print",
        "engraving",
        "painting",
        "artwork",
        "poster",
        "canvas",
        "frame",
        "sculpture",
        "drawing",
        "lithograph",
        "photograph",
        "art print",
        "wall art",
        "limited edition",
        "original",
        "gallery",
        "museum quality",
    ],
    "books": [
        "book",
        "novel",
        "textbook",
        "paperback",
        "hardcover",
        "magazine",
        "journal",
        "comic",
        "manga",
        "graphic novel",
        "encyclopedia",
        "dictionary",
        "publication",
    ],
    "toys": [
        "toy",
        "doll",
        "action figure",
        "lego",
        "puzzle",
        "board game",
        "card game",
        "stuffed animal",
        "plush",
        "collectible",
        "model",
        "hobby",
        "playing cards",
    ],
    "jewelry": [
        "jewelry",
        "necklace",
        "bracelet",
        "ring",
        "earrings",
        "watch",
        "pendant",
        "chain",
        "gold",
        "silver",
        "diamond",
        "gemstone",
        "precious metal",
    ],
    "food": [
        "food",
        "snack",
        "candy",
        "chocolate",
        "coffee",
        "tea",
        "spices",
        "sauce",
        "supplement",
        "vitamin",
        "protein",
        "gourmet",
        "organic",
        "natural food",
    ],
    "home_goods": [
        "kitchen",
        "cookware",
        "utensil",
        "dish",
        "plate",
        "bowl",
        "cup",
        "mug",
        "pan",
        "pot",
        "knife",
        "cutting board",
        "blender",
        "mixer",
        "appliance",
        "decor",
        "vase",
        "candle",
        "lamp",
        "furniture",
        "home",
    ],
}


def detect_product_category(contents: str) -> str:
    """Detect product category from free-text contents."""
    import re

    contents_lower = (contents or "").lower()

    for category, keywords in PRODUCT_CATEGORIES.items():
        for keyword in keywords:
            if " " in keyword:
                if keyword in contents_lower:
                    return category
            else:
                if re.search(rf"\b{re.escape(keyword)}\b", contents_lower):
                    return category

    for category, keywords in PRODUCT_CATEGORIES.items():
        for keyword in keywords:
            if keyword in contents_lower:
                return category

    return "default"
