"""Warehouse mapping and customs signer utilities."""

from __future__ import annotations

from typing import Dict


CUSTOMS_SIGNERS = {
    "California Apparel Supply": "Michael Chen",
    "California Outdoor Supply": "Sarah Martinez",
    "Premium Bedding Distribution": "David Rodriguez",
    "Natural Essentials Store": "Jennifer Lee",
    "West Coast Footwear": "Robert Kim",
    "California Fine Arts": "Emily Zhang",
    "Pacific Tech Supply": "James Wilson",
    "Nevada Apparel Supply": "Thomas Anderson",
    "Nevada Sporting Supply": "Lisa Thompson",
    "Nevada Home Essentials": "Maria Garcia",
    "Nevada Beauty Supply": "Amanda Foster",
    "Desert Shoes": "Christopher Moore",
    "Nevada Fine Arts": "Patricia Bennett",
    "Desert Electronics": "Daniel Harris",
    "Nevada Logistics Hub": "Jessica Martinez",
    "New York Fashion Supply": "William Taylor",
    "New York Outdoor Supplies": "Michelle Brown",
    "New York Home Essentials": "Brandon Clarke",
    "New York Beauty Essentials": "Victoria Wright",
    "East Coast Shoes": "Anthony Green",
    "New York Fine Arts": "Samantha King",
    "Silicon Alley Electronics": "Christopher Davis",
    "New York Logistics Hub": "Nicole Anderson",
}


WAREHOUSE_BY_CATEGORY: Dict[str, Dict[str, Dict[str, str]]] = {
    "California": {
        "bedding": {
            "name": "LA Home Goods Warehouse",
            "company": "Premium Bedding Distribution",
            "street1": "8500 Beverly Blvd",
            "street2": "Suite 120",
            "city": "Los Angeles",
            "state": "CA",
            "zip": "90048",
            "country": "US",
            "phone": "310-555-0199",
            "email": "bedding@lahomegoods.com",
        },
        "sporting": {
            "name": "LA Outdoor Gear Hub",
            "company": "California Outdoor Supply",
            "street1": "1200 S Broadway",
            "street2": "",
            "city": "Los Angeles",
            "state": "CA",
            "zip": "90015",
            "country": "US",
            "phone": "323-555-0155",
            "email": "sporting@laoutdoor.com",
        },
        "beauty": {
            "name": "Beauty & Wellness LA",
            "company": "Natural Essentials Store",
            "street1": "8500 Beverly Blvd",
            "street2": "Suite 120",
            "city": "Los Angeles",
            "state": "CA",
            "zip": "90048",
            "country": "US",
            "phone": "310-555-0199",
            "email": "beauty@beautywellnessla.com",
        },
        "apparel": {
            "name": "LA Fashion District Warehouse",
            "company": "California Apparel Supply",
            "street1": "1200 S Broadway",
            "street2": "Suite 100",
            "city": "Los Angeles",
            "state": "CA",
            "zip": "90015",
            "country": "US",
            "phone": "213-555-0166",
            "email": "apparel@lafashion.com",
        },
        "footwear": {
            "name": "LA Footwear Warehouse",
            "company": "West Coast Shoes",
            "street1": "1200 S Broadway",
            "street2": "Suite 150",
            "city": "Los Angeles",
            "state": "CA",
            "zip": "90015",
            "country": "US",
            "phone": "213-555-0177",
            "email": "footwear@westcoastshoes.com",
        },
        "art": {
            "name": "LA Arts District Warehouse",
            "company": "California Fine Arts",
            "street1": "8500 Beverly Blvd",
            "street2": "Suite 200",
            "city": "Los Angeles",
            "state": "CA",
            "zip": "90048",
            "country": "US",
            "phone": "310-555-0188",
            "email": "art@lafinearts.com",
        },
        "electronics": {
            "name": "LA Tech Warehouse",
            "company": "Silicon Beach Electronics",
            "street1": "1500 E Olympic Blvd",
            "street2": "Suite 300",
            "city": "Los Angeles",
            "state": "CA",
            "zip": "90021",
            "country": "US",
            "phone": "213-555-0199",
            "email": "tech@siliconbeach.com",
        },
        "default": {
            "name": "LA General Warehouse",
            "company": "California Distribution Center",
            "street1": "1500 E Olympic Blvd",
            "street2": "",
            "city": "Los Angeles",
            "state": "CA",
            "zip": "90021",
            "country": "US",
            "phone": "213-555-0100",
            "email": "shipping@ladistribution.com",
        },
    },
    "New York": {
        "bedding": {
            "name": "NYC Home Goods Warehouse",
            "company": "New York Home Essentials",
            "street1": "246 E 116th St",
            "street2": "Suite 200",
            "city": "New York",
            "state": "NY",
            "zip": "10029",
            "country": "US",
            "phone": "646-600-6012",
            "email": "bedding@nyhomegoods.com",
        },
        "sporting": {
            "name": "NYC Outdoor Gear Hub",
            "company": "New York Sporting Supply",
            "street1": "246 E 116th St",
            "street2": "Suite 300",
            "city": "New York",
            "state": "NY",
            "zip": "10029",
            "country": "US",
            "phone": "646-600-6012",
            "email": "sporting@nyoutdoor.com",
        },
        "beauty": {
            "name": "NYC Beauty & Wellness",
            "company": "New York Beauty Essentials",
            "street1": "246 E 116th St",
            "street2": "Suite 400",
            "city": "New York",
            "state": "NY",
            "zip": "10029",
            "country": "US",
            "phone": "646-600-6012",
            "email": "beauty@nycwellness.com",
        },
        "apparel": {
            "name": "NYC Garment District Warehouse",
            "company": "New York Fashion Supply",
            "street1": "246 E 116th St",
            "street2": "Suite 500",
            "city": "New York",
            "state": "NY",
            "zip": "10029",
            "country": "US",
            "phone": "646-600-6013",
            "email": "apparel@nyfashion.com",
        },
        "footwear": {
            "name": "NYC Footwear Warehouse",
            "company": "East Coast Shoes",
            "street1": "246 E 116th St",
            "street2": "Suite 600",
            "city": "New York",
            "state": "NY",
            "zip": "10029",
            "country": "US",
            "phone": "646-600-6014",
            "email": "footwear@eastcoastshoes.com",
        },
        "art": {
            "name": "NYC Gallery District Warehouse",
            "company": "New York Fine Arts",
            "street1": "246 E 116th St",
            "street2": "Suite 700",
            "city": "New York",
            "state": "NY",
            "zip": "10029",
            "country": "US",
            "phone": "646-600-6015",
            "email": "art@nyfinearts.com",
        },
        "electronics": {
            "name": "NYC Tech Warehouse",
            "company": "Silicon Alley Electronics",
            "street1": "246 E 116th St",
            "street2": "Suite 800",
            "city": "New York",
            "state": "NY",
            "zip": "10029",
            "country": "US",
            "phone": "646-600-6016",
            "email": "tech@siliconalley.com",
        },
        "default": {
            "name": "NYC Distribution Center",
            "company": "New York Logistics Hub",
            "street1": "246 E 116th St",
            "street2": "",
            "city": "New York",
            "state": "NY",
            "zip": "10029",
            "country": "US",
            "phone": "646-600-6012",
            "email": "shipping@nycdistro.com",
        },
    },
    "Nevada": {
        "bedding": {
            "name": "Las Vegas Home Goods Warehouse",
            "company": "Nevada Home Essentials",
            "street1": "3900 Paradise Rd",
            "street2": "Suite 100",
            "city": "Las Vegas",
            "state": "NV",
            "zip": "89169",
            "country": "US",
            "phone": "702-555-0100",
            "email": "bedding@lvhomegoods.com",
        },
        "sporting": {
            "name": "Las Vegas Outdoor Gear Hub",
            "company": "Nevada Sporting Supply",
            "street1": "3900 Paradise Rd",
            "street2": "Suite 200",
            "city": "Las Vegas",
            "state": "NV",
            "zip": "89169",
            "country": "US",
            "phone": "702-555-0101",
            "email": "sporting@lvoutdoor.com",
        },
        "beauty": {
            "name": "Las Vegas Beauty & Wellness",
            "company": "Nevada Beauty Supply",
            "street1": "3900 Paradise Rd",
            "street2": "Suite 300",
            "city": "Las Vegas",
            "state": "NV",
            "zip": "89169",
            "country": "US",
            "phone": "702-555-0102",
            "email": "beauty@lvbeauty.com",
        },
        "apparel": {
            "name": "Las Vegas Fashion Warehouse",
            "company": "Nevada Apparel Supply",
            "street1": "3900 Paradise Rd",
            "street2": "Suite 400",
            "city": "Las Vegas",
            "state": "NV",
            "zip": "89169",
            "country": "US",
            "phone": "702-555-0103",
            "email": "apparel@lvfashion.com",
        },
        "footwear": {
            "name": "Las Vegas Footwear Warehouse",
            "company": "Desert Shoes",
            "street1": "3900 Paradise Rd",
            "street2": "Suite 500",
            "city": "Las Vegas",
            "state": "NV",
            "zip": "89169",
            "country": "US",
            "phone": "702-555-0104",
            "email": "footwear@desertshoes.com",
        },
        "art": {
            "name": "Las Vegas Arts Warehouse",
            "company": "Nevada Fine Arts",
            "street1": "3900 Paradise Rd",
            "street2": "Suite 600",
            "city": "Las Vegas",
            "state": "NV",
            "zip": "89169",
            "country": "US",
            "phone": "702-555-0105",
            "email": "art@lvfinearts.com",
        },
        "electronics": {
            "name": "Las Vegas Tech Warehouse",
            "company": "Desert Electronics",
            "street1": "3900 Paradise Rd",
            "street2": "Suite 700",
            "city": "Las Vegas",
            "state": "NV",
            "zip": "89169",
            "country": "US",
            "phone": "702-555-0106",
            "email": "tech@deserttech.com",
        },
        "default": {
            "name": "Las Vegas Distribution Center",
            "company": "Nevada Logistics Hub",
            "street1": "3900 Paradise Rd",
            "street2": "Suite 200",
            "city": "Las Vegas",
            "state": "NV",
            "zip": "89169",
            "country": "US",
            "phone": "702-555-0188",
            "email": "shipping@lasvegasdistro.com",
        },
    },
}

STORE_ADDRESSES = {
    "California": {
        "Los Angeles": WAREHOUSE_BY_CATEGORY["California"]["default"],
    },
    "New York": {
        "New York": WAREHOUSE_BY_CATEGORY["New York"]["default"],
    },
    "Nevada": {
        "Las Vegas": WAREHOUSE_BY_CATEGORY["Nevada"]["default"],
    },
}

CA_STORE_ADDRESSES = STORE_ADDRESSES["California"]


def get_customs_signer(warehouse_address: dict) -> str:
    """Return customs signer name for a warehouse company."""
    company = warehouse_address.get("company", "")
    return CUSTOMS_SIGNERS.get(company, "Shipping Manager")


def get_warehouse_address(state: str, category: str) -> dict:
    """Select warehouse address by origin state and product category."""
    if state not in WAREHOUSE_BY_CATEGORY:
        state = "California"
    state_warehouses = WAREHOUSE_BY_CATEGORY[state]
    if category in state_warehouses:
        return state_warehouses[category]
    return state_warehouses.get("default", next(iter(state_warehouses.values())))
