"""make_parcel_id_nullable

Revision ID: 41963d524981
Revises: 72c02b9d8f35
Create Date: 2025-11-04 07:18:28.883234+00:00

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '41963d524981'
down_revision: Union[str, None] = '72c02b9d8f35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_shipment_events_shipment_id'), 'shipment_events', ['shipment_id'], unique=False)
    op.alter_column('shipments', 'parcel_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipments', 'parcel_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_shipment_events_shipment_id'), table_name='shipment_events')
    # ### end Alembic commands ###
