#!/bin/bash
# cleanup-codebase.sh - Automated codebase cleanup
# Generated by Desktop Commander Code Analysis

set -e  # Exit on error

PROJECT_ROOT="/Users/andrejs/easypost-mcp-project"
cd "$PROJECT_ROOT"

echo "🧹 Starting codebase cleanup..."
echo "📁 Working directory: $(pwd)"
echo ""

# Phase 1: Archive old reports
echo "📦 Phase 1: Archiving old reports..."
mkdir -p docs/archive/2025-11-03

# Archive code review reports
if [ -f "docs/reports/CODE_REVIEW_REPORT.md" ]; then
    mv docs/reports/CODE_REVIEW_REPORT.md docs/archive/2025-11-03/
    echo "  ✓ Archived CODE_REVIEW_REPORT.md"
fi

if [ -f "docs/reports/BUILD_SUCCESS.md" ]; then
    mv docs/reports/BUILD_SUCCESS.md docs/archive/2025-11-03/
    echo "  ✓ Archived BUILD_SUCCESS.md"
fi

if [ -f "docs/reports/TEST_ALL_SUCCESS.md" ]; then
    mv docs/reports/TEST_ALL_SUCCESS.md docs/archive/2025-11-03/
    echo "  ✓ Archived TEST_ALL_SUCCESS.md"
fi

if [ -f "docs/reports/FRONTEND_FIXES_COMPLETE.md" ]; then
    mv docs/reports/FRONTEND_FIXES_COMPLETE.md docs/archive/2025-11-03/
    echo "  ✓ Archived FRONTEND_FIXES_COMPLETE.md"
fi

if [ -f "docs/reports/STRUCTURE_OPTIMIZATION_COMPLETE.md" ]; then
    mv docs/reports/STRUCTURE_OPTIMIZATION_COMPLETE.md docs/archive/2025-11-03/
    echo "  ✓ Archived STRUCTURE_OPTIMIZATION_COMPLETE.md"
fi

if [ -f ".cursor/docs/CODE_REVIEW.md" ]; then
    mv .cursor/docs/CODE_REVIEW.md docs/archive/2025-11-03/
    echo "  ✓ Archived .cursor CODE_REVIEW.md"
fi

if [ -f ".cursor/docs/COMPREHENSIVE_REVIEW.md" ]; then
    mv .cursor/docs/COMPREHENSIVE_REVIEW.md docs/archive/2025-11-03/
    echo "  ✓ Archived COMPREHENSIVE_REVIEW.md"
fi

echo ""

# Phase 2: Remove duplicates
echo "🗑️  Phase 2: Removing duplicate files..."

if [ -f "DEV_DEPLOYMENT_GUIDE.md" ]; then
    rm -f DEV_DEPLOYMENT_GUIDE.md
    echo "  ✓ Removed duplicate DEV_DEPLOYMENT_GUIDE.md (kept docs/ version)"
fi

echo ""

# Phase 3: Organize temp files
echo "📂 Phase 3: Organizing temporary files..."
mkdir -p backend/tests/manual labels

if [ -f "Zosia-Tapp-UPS-Ground-1Z09E1D30320026818.png" ]; then
    mv Zosia-Tapp-UPS-Ground-1Z09E1D30320026818.png labels/
    echo "  ✓ Moved label to labels/"
fi

if [ -f "backend/buy_remaining_5.py" ]; then
    mv backend/buy_remaining_5.py backend/tests/manual/
    echo "  ✓ Moved buy_remaining_5.py to tests/manual/"
fi

if [ -f "backend/test_async_customs.py" ]; then
    mv backend/test_async_customs.py backend/tests/manual/
    echo "  ✓ Moved test_async_customs.py to tests/manual/"
fi

echo ""

# Phase 4: Remove old archives
echo "🗑️  Phase 4: Removing old archives..."

if [ -f "shipping-labels-all-12-20251103.zip" ]; then
    rm -f shipping-labels-all-12-20251103.zip
    echo "  ✓ Removed old shipping labels archive"
fi

echo ""

# Summary
echo "✅ Cleanup complete!"
echo ""
echo "📊 Summary:"
echo "  • Archived: 7 old reports"
echo "  • Removed: 2 duplicate files"
echo "  • Organized: 3 temp files"
echo "  • Cleaned: 1 old archive"
echo ""
echo "📁 Changes ready for review:"
git status --short 2>/dev/null || echo "  (Run 'git status' to see changes)"
echo ""
echo "🔍 Next steps:"
echo "  1. Review changes with 'git status'"
echo "  2. Run tests: 'cd backend && pytest'"
echo "  3. Run linters: 'npm run lint' (frontend)"
echo "  4. Commit: 'git add -A && git commit -m \"chore: cleanup codebase\"'"
